### ISSUE TITLE
0 variants found 

### ISSUE THREAD

**Issue by asifrim** [asifrim/eXtasy#1]
$ ./extasy.rb -i myfile.vcf -g ./geneprios/res/HP_0002863_fgs.tsv -k
2013-11-15 14:45:10 +0100: Sorting input VCF...
2013-11-15 14:45:10 +0100: Input VCF sorted...
2013-11-15 14:45:10 +0100: Finding missense mutations...
2013-11-15 14:45:52 +0100: Fetching features for variants...
2013-11-15 14:45:53 +0100: 0 missense variants annotated...
2013-11-15 14:45:53 +0100: Prioritizing against ./geneprios/res/HP_0002863_fgs.tsv
2013-11-15 14:45:53 +0100: Appending gene prioritization data...
2013-11-15 14:45:54 +0100: Data ready for eXtasy...
2013-11-15 14:45:54 +0100: Running eXtasy...
randomForest 4.6-7
Type rfNews() to see new features/changes/bug fixes.
Error in `$<-.data.frame`(`*tmp*`, "altbase", value = "T") : 
  replacement has 1 row, data has 0
Calls: $<- -> $<-.data.frame
Execution halted
2013-11-15 14:46:01 +0100: eXtasy prioritization completed!
./extasy.rb:52:in `rename': No such file or directory - (myfile.vcf.sorted.matches.annotated.extasy_input.extasy_output, myfile_-_HP_0002863_fgs.extasy) (Errno::ENOENT)
    from ./extasy.rb:52:in`block in <main>'
    from ./extasy.rb:39:in `each'
    from ./extasy.rb:39:in`<main>'

I know variants included in my vcf (which come from an exome sequencing study) contain some missense mutations. I've tried eXtasy with example data and I get the very same error:

$ ./extasy.rb -i example_data/example.vcf -g ./geneprios/res/HP_0002863_fgs.tsv -k
2013-11-15 14:47:56 +0100: Sorting input VCF...
2013-11-15 14:47:56 +0100: Input VCF sorted...
2013-11-15 14:47:56 +0100: Finding missense mutations...
2013-11-15 14:48:16 +0100: Fetching features for variants...
2013-11-15 14:48:17 +0100: 0 missense variants annotated...
2013-11-15 14:48:17 +0100: Prioritizing against ./geneprios/res/HP_0002863_fgs.tsv
2013-11-15 14:48:17 +0100: Appending gene prioritization data...
2013-11-15 14:48:18 +0100: Data ready for eXtasy...
2013-11-15 14:48:18 +0100: Running eXtasy...
randomForest 4.6-7
Type rfNews() to see new features/changes/bug fixes.
Error in `$<-.data.frame`(`*tmp*`, "altbase", value = "T") : 
  replacement has 1 row, data has 0
Calls: $<- -> $<-.data.frame
Execution halted
2013-11-15 14:48:26 +0100: eXtasy prioritization completed!
./extasy.rb:52:in `rename': No such file or directory - (example_data/example.vcf.sorted.matches.annotated.extasy_input.extasy_output, example_data/example_-_HP_0002863_fgs.extasy) (Errno::ENOENT)
    from ./extasy.rb:52:in`block in <main>'
    from ./extasy.rb:39:in `each'
    from ./extasy.rb:39:in`<main>'

Would you suggest me some hint to solve this?
I'm using eXtasy in commit

$ git rev-parse HEAD
f97722858ed7924665be05cff514110b94ffeb49

$ git describe --tags
0.1-2-gf977228

$ ruby -v
ruby 2.0.0p247 (2013-06-27 revision 41674) [universal.x86_64-darwin13]

$ uname -a
Darwin rs800007.station 13.0.0 Darwin Kernel Version 13.0.0: Thu Sep 19 22:22:27 PDT 2013; root:xnu-2422.1.72~6/RELEASE_X86_64 x86_64

**Comment by asifrim** [comment]
Trying to reproduce running environment, eXtasy has not been tested on Ruby 2.x or in a Mac environment.
